# sparkConsumer01.py
- local[*]에서 실행 확인됨
- spark://34.125.136.103:30077에서 오류남
